"use client";

/* The same water/sky shader as the landing page hero
 * (features/landing/hero/scene.ts -- a generated file, ported verbatim from
 * the demo build and never hand-edited). Only the water/sky layer is used
 * here: no vessel, no towfish, no scroll-driven dive, no instrument HUD --
 * just the shader held at the hero's own "at the surface" camera height
 * (APPROVED.camY) so it reads as a static ambient shot rather than the
 * survey sequence. Shader + tuning are copied, not imported, because the
 * source file is regenerated by the port script and exports nothing.
 */
import { useEffect, useRef } from "react";
import * as THREE from "three";

import { useReducedMotion } from "@/hooks/useReducedMotion";

const VERT = `attribute vec2 p; void main(){ gl_Position = vec4(p, 0.0, 1.0); }`;

const FRAG = `
precision highp float;
uniform vec2  uRes;
uniform float uTime;
uniform float camY, horizon, seabedDepth, quality;
uniform float sunAz, sunEl, sunStr, sunTight, sunGlow;
uniform float horR, horG, horB, zenR, zenG, zenB, skyGrad, cloudAmt, cloudCover, cloudScale;
uniform float swellLen, swellAmp, medLen, medAmp, chopStr, waveSpeed, windDir, detailFall;
uniform float seaR, seaG, seaB, fresnelF0, glitterPow, glitterStr, hazeAmt;
uniform float floorScale, sandR, sandG, sandB, sandGrain;
uniform float causticStrength, causticSharp, causticSpeed, causticBeat, causticFade;
uniform float fogDensity, absR, absG, absB;
uniform float rayStr, rayFreq, rayReach, raySharp, rayDepthFade;
uniform float bubbleAmount, bubbleSize, bubbleSpeed, moteAmount, moteSize;
uniform float exposure, vignette, grain;

float h21(vec2 p){ return fract(sin(dot(p, vec2(127.1,311.7)))*43758.5453); }
float nse(vec2 p){
  vec2 i=floor(p), f=fract(p); f=f*f*(3.0-2.0*f);
  return mix(mix(h21(i),h21(i+vec2(1,0)),f.x), mix(h21(i+vec2(0,1)),h21(i+vec2(1,1)),f.x), f.y);
}
float fbm(vec2 p){ float a=0.5,v=0.0; for(int i=0;i<5;i++){ v+=a*nse(p); p*=2.03; a*=0.5; } return v; }
vec2 fbmGrad(vec2 p, float e){
  float c=fbm(p);
  return vec2(fbm(p+vec2(e,0.0))-c, fbm(p+vec2(0.0,e))-c)/e;
}
vec3 sunDirection(){ return normalize(vec3(sin(sunAz), sunEl, -cos(sunAz))); }

vec3 skyColor(vec3 dir){
  float el = clamp(dir.y, -0.15, 1.0);
  vec3 c = mix(vec3(horR,horG,horB), vec3(zenR,zenG,zenB), pow(clamp(el,0.0,1.0), skyGrad));
  vec3 sd = sunDirection();
  float al = max(dot(normalize(dir), sd), 0.0);
  c += vec3(1.0,0.96,0.88)*pow(al,sunTight)*sunStr;
  c += vec3(1.0,0.94,0.84)*pow(al,12.0)*sunGlow*0.30;
  if (cloudAmt > 0.001 && dir.y > 0.012){
    float ct = 1.0/max(dir.y,0.012);
    vec2 cuv = (dir.xz*ct)*cloudScale*0.06 + vec2(uTime*0.004, uTime*0.002);
    float f = fbm(cuv) + fbm(cuv*2.7)*0.35;
    float m = smoothstep(cloudCover, cloudCover+0.30, f)*smoothstep(0.012,0.16,dir.y);
    c = mix(c, mix(vec3(0.72), vec3(1.0), smoothstep(0.0,0.6,f)), m*cloudAmt);
  }
  return c;
}

void addWave(inout vec2 s, vec2 p, vec2 d, float len, float amp, float t){
  float k = 6.2831853/max(len,0.001);
  s += d*(cos(dot(d,p)*k + t)*amp*k);
}
float waveHeight(vec2 p){
  float t = uTime*waveSpeed;
  vec2 w = vec2(cos(windDir), sin(windDir));
  vec2 w2 = vec2(cos(windDir+0.7), sin(windDir+0.7));
  float k1 = 6.2831853/swellLen, k2 = 6.2831853/medLen;
  return sin(dot(w,p)*k1 + t*0.55)*swellAmp
       + sin(dot(w2,p)*k2 + t*1.05)*medAmp;
}
vec3 waveNormal(vec2 p, float dist){
  float t = uTime*waveSpeed;
  float detail = exp(-dist*detailFall);
  p += (vec2(fbm(p*0.018), fbm(p*0.018+7.3))-0.5)*9.0;
  vec2 s = vec2(0.0);
  vec2 w  = vec2(cos(windDir), sin(windDir));
  vec2 w2 = vec2(cos(windDir+0.7), sin(windDir+0.7));
  vec2 w3 = vec2(cos(windDir-0.9), sin(windDir-0.9));
  addWave(s,p,w, swellLen,       swellAmp,       t*0.55);
  addWave(s,p,w2,swellLen*0.63,  swellAmp*0.55,  t*0.61);
  float md = mix(0.35,1.0,detail);
  addWave(s,p,w2,medLen,         medAmp*md,      t*1.05);
  addWave(s,p,w3,medLen*0.66,    medAmp*0.72*md, t*1.24);
  addWave(s,p,w, medLen*0.41,    medAmp*0.46*md, t*1.51);
  vec2 drift = w*(t*0.6);
  s += fbmGrad(p*0.22+drift,       0.35)*chopStr*1.00*detail;
  s += fbmGrad(p*0.65-drift*1.7,   0.18)*chopStr*0.55*detail;
  if (quality > 0.5) s += fbmGrad(p*1.80+drift*2.6, 0.08)*chopStr*0.28*detail*detail;
  return normalize(vec3(-s.x, 1.0, -s.y));
}

vec3 waterAt(float depthM){
  vec3 c = vec3(0.380,0.600,0.712);
  c = mix(c, vec3(0.059,0.294,0.439), smoothstep( 1.0,27.0,depthM));
  c = mix(c, vec3(0.027,0.166,0.408), smoothstep(17.0,43.0,depthM));
  c = mix(c, vec3(0.004,0.054,0.261), smoothstep(31.0,57.0,depthM));
  return c;
}

float causticLayer(vec2 p, float t){
  float v = 0.0;
  for (int i=0;i<3;i++){
    float fi=float(i);
    vec2 q = p*(1.0+fi*0.8) + vec2(t*(0.30+fi*0.11), -t*(0.22+fi*0.09));
    v += (1.0-abs(fbm(q)*2.0-1.0))*(1.0-fi*0.22);
  }
  return pow(clamp(v/2.34,0.0,1.0), causticSharp);
}
float caustics(vec2 uv, float t){
  float c  = causticLayer(uv, t);
  c += causticLayer(uv*causticBeat+23.0, -t*0.62)*0.55;
  if (quality > 0.5) c += causticLayer(uv*causticBeat*2.7+71.0, t*0.34)*0.28;
  return c;
}

vec3 shadeAbove(vec3 ro, vec3 rd, float surfH){
  vec3 sd = sunDirection();
  if (rd.y >= -0.0008){
    vec3 c = skyColor(rd);
    float band = 1.0 - smoothstep(0.0, 0.06, rd.y);
    return mix(c, vec3(horR,horG,horB), band*0.55*hazeAmt);
  }
  float t = max(ro.y - surfH, 0.05)/(-rd.y);
  vec3  p = ro + rd*t;
  vec3  N = waveNormal(p.xz, t);
  float NdotV = max(dot(N,-rd), 0.0);
  float F = fresnelF0 + (1.0-fresnelF0)*pow(1.0-NdotV, 5.0);
  vec3 R = reflect(rd, N); R.y = abs(R.y);
  vec3 c = mix(vec3(seaR,seaG,seaB), skyColor(R), clamp(F,0.0,1.0));
  float facets = pow(max(dot(R,sd),0.0), glitterPow)*(0.65+0.35*fbm(p.xz*0.8+uTime*0.05));
  c += vec3(1.0,0.97,0.90)*facets*glitterStr*exp(-t*detailFall*0.55);
  float hz = 1.0 - exp(-t*0.0016);
  return mix(c, skyColor(vec3(rd.x,0.02,rd.z)), hz*hazeAmt);
}

vec3 shadeBelow(vec3 ro, vec3 rd, vec2 frag, float surfH){
  vec3 sd = sunDirection();
  float eyeDepth = max(0.0, surfH - ro.y);
  float floorY = -seabedDepth;
  vec3 col; float underPath;

  if (rd.y > 0.0008){
    float t = max(surfH - ro.y, 0.05)/rd.y;
    vec3  p = ro + rd*t;
    vec3  N = waveNormal(p.xz, t);
    float ang = acos(clamp(rd.y, -1.0, 1.0));
    float crit = 0.8483;
    float win = smoothstep(crit + 0.10, crit - 0.16, ang);
    vec3 thr = refract(rd, -N, 1.0/1.333);
    vec3 through = (dot(thr,thr) < 0.0001) ? skyColor(vec3(rd.x,0.9,rd.z)) : skyColor(normalize(thr));
    col = mix(waterAt(eyeDepth + 6.0)*1.15, through, clamp(win,0.0,1.0));
    col += vec3(0.72,0.93,1.0)*pow(max(dot(reflect(rd,N),sd),0.0), 90.0)*0.25;
    underPath = t;
  } else {
    float t = (ro.y - floorY)/max(-rd.y, 1e-4);
    vec3  p = ro + rd*t;
    vec2 fuv = (p.xz + vec2(53.0,17.0))*(floorScale*0.1);
    float c = caustics(fuv, uTime*causticSpeed);
    float g = fbm(fuv*6.0)*sandGrain;
    float cFade = mix(1.0, exp(-t*0.09), causticFade);
    col  = vec3(sandR,sandG,sandB)*(0.55+g);
    col += vec3(0.85,0.95,1.0)*c*causticStrength*cFade;
    underPath = t;
  }

  vec3 ab = vec3(absR,absG,absB);
  ab /= max((ab.r+ab.g+ab.b)/3.0, 1e-4);
  col = mix(col, waterAt(eyeDepth), clamp(1.0 - exp(-underPath*fogDensity*ab), 0.0, 1.0));

  vec3 sdw = normalize(mix(sd, vec3(0.0, 1.0, 0.0), 0.35));
  if (sdw.z < -0.001){
    vec2 sunUV = vec2(-sdw.x/sdw.z, -sdw.y/sdw.z + horizon);
    vec2 sunFrag = vec2(sunUV.x*(uRes.y/uRes.x) + 0.5, sunUV.y + 0.5);
    vec2 d = frag - sunFrag; d.x *= uRes.x/uRes.y;
    float r = length(d);
    float a2 = atan(d.x, -d.y);
    float down = -d.y/max(r,1e-4);
    float shafts = pow(clamp(fbm(vec2(a2*rayFreq, uTime*0.04)),0.0,1.0), raySharp);
    shafts *= smoothstep(-0.10,0.70,down);
    shafts *= smoothstep(rayReach,0.0,r);
    shafts *= 0.70 + 0.30*sin(uTime*0.55 + a2*6.0);
    shafts *= mix(1.0, smoothstep(0.0,0.62,frag.y), rayDepthFade);
    col += vec3(0.72,0.93,1.0)*shafts*rayStr*0.25;
  }

  float bub = 0.0;
  for (int i=0;i<4;i++){
    float fi=float(i); float cx = h21(vec2(fi,3.0));
    for (int j=0;j<4;j++){
      float fj=float(j); float seed = h21(vec2(fi*9.1, fj*4.7));
      float y = fract(seed + uTime*bubbleSpeed*(0.55+seed*0.9));
      vec2 bp = vec2(cx + sin((y+seed)*9.0)*0.012, y*0.92+0.04) - frag;
      bp.x *= uRes.x/uRes.y;
      bub += smoothstep(bubbleSize*(0.5+seed)*(0.6+y*0.8), 0.0, length(bp))*(0.35+0.65*seed);
    }
  }
  col += vec3(0.85,0.96,1.0)*bub*bubbleAmount;

  float motes = 0.0;
  for (int i=0;i<12;i++){
    float fi=float(i);
    vec2 mp = vec2(h21(vec2(fi,1.3)), fract(h21(vec2(fi,5.9)) + uTime*0.006));
    vec2 dd = mp - frag; dd.x *= uRes.x/uRes.y;
    motes += smoothstep(moteSize*(0.4+h21(vec2(fi,8.8))), 0.0, length(dd))*0.5;
  }
  col += vec3(0.8,0.93,1.0)*motes*moteAmount*0.25;
  return col;
}

void main(){
  vec2 frag = gl_FragCoord.xy/uRes;
  vec2 uv   = (gl_FragCoord.xy - 0.5*uRes)/uRes.y;
  vec3 ro = vec3(0.0, camY, 0.0);
  vec3 rd = normalize(vec3(uv.x, uv.y - horizon, -1.0));

  float surfH = waveHeight(vec2(0.0, 0.0));
  float w = smoothstep(-0.9, 0.9, camY - surfH);
  vec3 col;
  if (w > 0.995)      col = shadeAbove(ro, rd, surfH);
  else if (w < 0.005) col = shadeBelow(ro, rd, frag, surfH);
  else                col = mix(shadeBelow(ro, rd, frag, surfH), shadeAbove(ro, rd, surfH), w);

  col *= exposure;
  col = col/(1.0 + col*0.55);
  float lum = dot(col, vec3(0.299,0.587,0.114));
  col = mix(vec3(lum), col, 1.18);
  vec2 vc = (frag-0.5)*vec2(1.06,1.0);
  float vigAmt = mix(0.22, vignette, clamp(-camY/8.0, 0.0, 1.0));
  col *= clamp(1.0 - vigAmt*pow(clamp(length(vc)*1.42,0.0,1.0),2.15), 0.0, 1.0);
  col += (h21(gl_FragCoord.xy + fract(uTime)) - 0.5)*grain;
  gl_FragColor = vec4(clamp(col,0.0,1.0), 1.0);
}
`;

/* The hero's own approved tuning (features/landing/hero/scene.ts), held at
 * camY = 6.75 -- "above the waterline, vessel sailing" -- so this always
 * takes the shadeAbove() branch: sky, horizon and wave surface only. */
const APPROVED: Record<string, number> = {
  camY: 6.75, horizon: 0.125, seabedDepth: 30, quality: 1,
  sunAz: 0, sunEl: 0.115, sunStr: 0.22, sunTight: 3200, sunGlow: 0.55,
  horR: 0.6, horG: 0.86, horB: 1, zenR: 0.05, zenG: 0.4, zenB: 0.86,
  skyGrad: 0.42, cloudAmt: 0.5, cloudCover: 0.84, cloudScale: 1.85,
  swellLen: 52, swellAmp: 0.55, medLen: 13, medAmp: 0.2, chopStr: 0.55,
  waveSpeed: 0.55, windDir: 0.3, detailFall: 0.024,
  seaR: 0.035, seaG: 0.135, seaB: 0.3, fresnelF0: 0.022, glitterPow: 260,
  glitterStr: 2.1, hazeAmt: 0.62,
  floorScale: 6, sandR: 0.45, sandG: 0.44, sandB: 0.78, sandGrain: 0.87,
  causticStrength: 2.39, causticSharp: 14.8, causticSpeed: 0.79, causticBeat: 4, causticFade: 0.32,
  fogDensity: 0.03, absR: 2.9, absG: 1.2, absB: 0.6,
  rayStr: 2.56, rayFreq: 27.8, rayReach: 2, raySharp: 6.3, rayDepthFade: 0.92,
  bubbleAmount: 2.63, bubbleSize: 0.0067, bubbleSpeed: 0.2, moteAmount: 0.47, moteSize: 0.013,
  exposure: 1.2, vignette: 0.45, grain: 0.012,
};

export function HeroWaterBackdrop() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const reducedMotion = useReducedMotion();

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const canvasEl: HTMLCanvasElement = canvas;

    const renderer = new THREE.WebGLRenderer({ canvas: canvasEl, antialias: true, alpha: false });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.6));

    const scene = new THREE.Scene();
    const camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);

    const uniforms: Record<string, { value: number | THREE.Vector2 }> = {
      uRes: { value: new THREE.Vector2(1, 1) },
      uTime: { value: 0 },
    };
    for (const [key, value] of Object.entries(APPROVED)) uniforms[key] = { value };

    scene.add(
      new THREE.Mesh(
        new THREE.PlaneGeometry(2, 2),
        new THREE.ShaderMaterial({
          uniforms,
          vertexShader: VERT.replace("attribute vec2 p;", "").replace("vec4(p, 0.0, 1.0)", "vec4(position.xy, 0.0, 1.0)"),
          fragmentShader: FRAG,
          depthTest: false,
          depthWrite: false,
        })
      )
    );

    // Set once the loop below exists. A resize while the loop is PAUSED still
    // has to repaint -- the canvas was resized under a frame that will not be
    // drawn again on its own, so without this the backdrop stretches or blanks
    // and stays that way until something else happens to resume it.
    let repaintIfPaused: (() => void) | null = null;

    function resize() {
      const w = canvasEl.clientWidth;
      const h = canvasEl.clientHeight;
      if (w === 0 || h === 0) return;
      renderer.setSize(w, h, false);
      (uniforms.uRes.value as THREE.Vector2).set(w, h);
      repaintIfPaused?.();
    }
    const ro = new ResizeObserver(resize);
    ro.observe(canvasEl);
    resize();

    /* The loop only runs when this shader is actually being looked at.
     *
     * It used to render unconditionally, forever, from mount until unmount.
     * That is expensive in a way the file does not look expensive: FRAG is a
     * full-screen raymarch with 5-octave fbm, caustics, god rays and bubbles,
     * evaluated per pixel at up to 1.6x device pixel ratio. On integrated
     * graphics it saturates the GPU, and a saturated GPU stalls the compositor
     * -- which the user does not experience as "the water is slow", they
     * experience it as clicks being dropped and navigation hanging, because
     * their click DID land and the frame showing it never came.
     *
     * Three cases, and the old loop got all three wrong:
     *
     *   off-screen   scrolled past, or on a page where it sits behind content
     *                that has grown taller than the viewport -- still rendered
     *   tab hidden   browsers throttle rAF here but do not reliably stop it
     *   reduced motion  it pinned uTime to 0 and then kept re-rendering the
     *                IDENTICAL frame 60 times a second, which is the worst of
     *                both: the accessibility preference was honoured visually
     *                and ignored entirely where it costs
     *
     * Paused is not blank: renderOnce() paints one frame so the backdrop is
     * still there, it has simply stopped animating.
     */
    let raf = 0;
    let running = false;
    let onScreen = true;
    let tabVisible = typeof document === "undefined" || !document.hidden;

    // Accumulated rather than derived from a fixed start, so resuming after a
    // pause continues the swell instead of jumping forward by however long the
    // page sat in a background tab.
    let elapsed = 0;
    let last = 0;

    const animated = !reducedMotion;
    const shouldRun = () => animated && onScreen && tabVisible;

    function renderOnce() {
      uniforms.uTime.value = elapsed;
      renderer.render(scene, camera);
    }

    function tick(now: number) {
      if (last === 0) last = now;
      elapsed += (now - last) / 1000;
      last = now;
      uniforms.uTime.value = elapsed;
      renderer.render(scene, camera);
      raf = requestAnimationFrame(tick);
    }

    function startLoop() {
      if (running || !shouldRun()) return;
      running = true;
      last = 0;
      raf = requestAnimationFrame(tick);
    }

    function stopLoop() {
      if (!running) return;
      cancelAnimationFrame(raf);
      running = false;
      last = 0;
    }

    const io = new IntersectionObserver(
      ([entry]) => {
        onScreen = entry.isIntersecting;
        if (shouldRun()) startLoop();
        else {
          stopLoop();
          if (onScreen) renderOnce();
        }
      },
      { threshold: 0 }
    );
    io.observe(canvasEl);

    function onVisibility() {
      tabVisible = !document.hidden;
      if (shouldRun()) startLoop();
      else stopLoop();
    }
    document.addEventListener("visibilitychange", onVisibility);

    repaintIfPaused = () => {
      if (!running) renderOnce();
    };

    if (shouldRun()) startLoop();
    else renderOnce();

    return () => {
      stopLoop();
      io.disconnect();
      document.removeEventListener("visibilitychange", onVisibility);
      ro.disconnect();
      renderer.dispose();
    };
  }, [reducedMotion]);

  return <canvas ref={canvasRef} aria-hidden className="!absolute inset-0 h-full w-full" />;
}
